language: android
dist: trusty # For oracleJDK fail errors, as per advice from https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/6


jdk:
  - oraclejdk8

android:
  components:
    - build-tools-29.0.2 # The BuildTools version used by the project
    - android-29 # The SDK version used to compile the project

before_install:
 - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
- ./gradlew check
- ./gradlew tests:test  
- if [ -n "$TRAVIS_TAG" ]; then
    wget  -O jdk-windows.zip https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.232-1.b09/java-1.8.0-openjdk-1.8.0.232-1.b09.ojdkbuild.windows.x86_64.zip;
    ./gradlew desktop:packrWindows32;
    ./gradlew desktop:packrWindows64;
    ./gradlew desktop:packrLinux32;
    ./gradlew desktop:packrLinux64;
    ./gradlew desktop:zipLinuxFilesForJar;
  fi
